create table attack (id integer not null auto_increment, timestamp varchar(255), detection_point_id integer, detection_system_id integer, resource_id integer, user_id integer, primary key (id))
create table attack_metadata (attack_id integer not null, metadata_id integer not null)
create table detection_point (id integer not null auto_increment, category varchar(255), label varchar(255), threshold_id integer, primary key (id))
create table detection_system (id integer not null auto_increment, detection_system_id varchar(255), ip_address tinyblob, primary key (id))
create table event (id integer not null auto_increment, timestamp varchar(255), detection_point_id integer, detection_system_id integer, resource_id integer, user_id integer, primary key (id))
create table event_metadata (event_id integer not null, metadata_id integer not null)
create table geo_location (id integer not null auto_increment, latitude double precision not null, longitude double precision not null, primary key (id))
create table `interval` (id integer not null auto_increment, duration integer, unit varchar(255), primary key (id))
create table ipaddress (id integer not null auto_increment, address varchar(255), geo_location tinyblob, primary key (id))
create table key_value_pair (id integer not null auto_increment, key varchar(255), value varchar(255), primary key (id))
create table resource (id integer not null auto_increment, location varchar(255), primary key (id))
create table response (id integer not null auto_increment, action varchar(255), active bit not null, timestamp varchar(255), detection_system_id integer, interval_id integer, user_id integer, primary key (id))
create table response_metadata (response_id integer not null, metadata_id integer not null)
create table threshold (id integer not null auto_increment, t_count integer, interval_id integer, primary key (id))
create table user (id integer not null auto_increment, ip_address tinyblob, username varchar(255), primary key (id))
alter table attack_metadata add constraint UK_bbudvpd8rk7ejftsybir8hxkl unique (metadata_id)
alter table event_metadata add constraint UK_kpngs6dpgqyc5yrnos21tgsj2 unique (metadata_id)
alter table response_metadata add constraint UK_78xls2e7mtshgxtik5dey4y71 unique (metadata_id)
alter table attack add constraint FK_s98tpuvqslroj348sg3sio3jf foreign key (detection_point_id) references detection_point (id)
alter table attack add constraint FK_dokpx7286ln9icedoii8usqcr foreign key (detection_system_id) references detection_system (id)
alter table attack add constraint FK_2pfeq8ihvpophdnwv45rw290 foreign key (resource_id) references resource (id)
alter table attack add constraint FK_trt3wyyi1vbk04im3sewj7xb7 foreign key (user_id) references user (id)
alter table attack_metadata add constraint FK_bbudvpd8rk7ejftsybir8hxkl foreign key (metadata_id) references key_value_pair (id)
alter table attack_metadata add constraint FK_bwg60u7mss38jbw93rsqdw2ti foreign key (attack_id) references attack (id)
alter table detection_point add constraint FK_log2mnu5axh69d1hn0agi78y foreign key (threshold_id) references threshold (id)
alter table event add constraint FK_cyiuhwt60r0nq5ej6j9wm27x0 foreign key (detection_point_id) references detection_point (id)
alter table event add constraint FK_iqyyd9crqnfm2q4q740ygm1e1 foreign key (detection_system_id) references detection_system (id)
alter table event add constraint FK_ei0063idkhgfh6pqv2hsfont1 foreign key (resource_id) references resource (id)
alter table event add constraint FK_p84ruvsg7mfwb2x5p7iq3q103 foreign key (user_id) references user (id)
alter table event_metadata add constraint FK_kpngs6dpgqyc5yrnos21tgsj2 foreign key (metadata_id) references key_value_pair (id)
alter table event_metadata add constraint FK_529qqhtc04ctd2hgelppi408x foreign key (event_id) references event (id)
alter table response add constraint FK_87uubvo2fgwwpbmfcfkp82a62 foreign key (detection_system_id) references detection_system (id)
alter table response add constraint FK_cqbci2wy6y9upuqsel4asb3fl foreign key (interval_id) references `interval` (id)
alter table response add constraint FK_1j5vg1wv52y5trquwxsa1bmno foreign key (user_id) references user (id)
alter table response_metadata add constraint FK_78xls2e7mtshgxtik5dey4y71 foreign key (metadata_id) references key_value_pair (id)
alter table response_metadata add constraint FK_8fixvnin48xn4ondt4fw729cc foreign key (response_id) references response (id)
alter table threshold add constraint FK_cmrw7h9idnjhcqd6mfv4w4u5d foreign key (interval_id) references `interval` (id)
